# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: Dino Nalbanski
# Description of the Site
description: Welcome to my homepage
# URL of Image of the Site
site-image: /WhatATheme/assets/images/meta.jpg
# Keywords of the Site
site-keywords: Site
# URL for the Image of custom Favicon
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: "/assets/images/formule_e1.jpg"

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: dnalbanski@gmail.com
#facebook_username: thedevslot
#twitter_username: thedevslot
#instagram_username: thedevslot
linkedin_username: dino-nalbanski-22a7a559/
#github_username:  thedevslot
youtube_channel_id: UC49bwlgPDJny01HKrE39GpA
#reddit_username: /
#behance_username: /
#dribbble_username: /
#spotify_username: /

# Google Analytics
google-analytics: UA-180266312-1

# Disqus
disqus-shortname: dnalb

# Name of the Author
author-name: Dino Nalbanski
# URL for the Image of the Author
author-image: https://photos.app.goo.gl/Hro86uwf9e7cx5uc6
# 60 Words About the Author
author-about: "Hi, my name is Dino and I am pleased to welcome you to my site! I created this personal webspace as a porfolio to showcase my work. 
There will be drawings I post in here as well as possibly videos and tutorials at a later stage."

# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/thedevslot

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
